server:
  port: 6100

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: false            # gateway关闭服务注册和发现
          lowerCaseServiceId: true  # 请求路径上的服务名配置为小写
      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        port: 17100
        dashboard: localhost:8748

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: gateway
  sleuth:
    sampler:
      probability: 1    #设置采样率默认为 0.1

  main:
    allow-bean-definition-overriding: true