server:
  port: 6002

spring:
  application:
    name: consumer

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 17101
        dashboard: localhost:8748

feign:
  sentinel:
    enabled: true    # 开启Feign和sentinel的自动适配