server:
  port: 6001

spring:
  application:
    name: provider

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1    #设置采样率默认为 0.1